[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#38a169"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7fafc"
textColor = "#1a202c"
font = "sans serif"
